export enum ListPricingCorridorsSortByDto {
  CORRIDOR_CODE = 'corridorCode',
  ORIGIN_COUNTRY_CODE = 'originCountryCode',
  DESTINATION_COUNTRY_CODE = 'destinationCountryCode',
  STATUS = 'status',
  CONFIDENCE_LEVEL = 'confidenceLevel',
  SETTLEMENT_CURRENCY = 'settlementCurrency',
  PRICING_SOURCE_TYPE = 'pricingSourceType',
  PRICING_CALIBRATION_BASIS = 'pricingCalibrationBasis',
  PRICING_REFERENCE_CORRIDOR_CODE = 'pricingReferenceCorridorCode',
  IS_ESTIMATED = 'isEstimated',
  REQUIRES_MANUAL_REVIEW = 'requiresManualReview',
  IS_VISIBLE = 'isVisible',
  IS_BOOKABLE = 'isBookable',
  IS_ACTIVE = 'isActive',
}